### ISSUE TITLE
ClojureScript support

### ISSUE THREAD

**Issue by Gonzih** [marick/structural-typing#4]
Hello there!

I must say that I love this project and idea in general. And because of my interestd I would also like to try this out in clojurescript enviroment. So my questions are:

Is clojurescript support planned at some point?
How hard is it to implement? Is your current implementation tied in any way to the jvm hosted clojure?

Thanks!

**Comment by marick** [comment]
It would probably not be too hard to port this to Clojurescript, though I know very little about Clojurescript. A problem is that all the tests are written in Midje, which does not work in ClojureScript. 

Since this library is going to be a building block for the next version of Midje, there's a considerable circular dependency problem.

**Comment by yatesco** [comment]
I have gotten around this restriction by developing everything in `cljc` code but only testing on the `jvm` side. For namespaces that don't make any `jvm` specific code it is as simple as renaming the extension.

Of course, if there _is_ `jvm` specific code then it must be dealt with separately.

This isn't ideal, but does go a long way towards a solution.

**Comment by marick** [comment]
I do encourage others to take a whack at this. These days, I'm thinking that I want to do frontend work in Elm, but obviously Clojurescript is important.

**Comment by pbaille** [comment]
It looks like a considerable amount of work to port to cljs, there are many dependencies that are JVM only. But I think it clearly worth the effort.
